version: "3.8"

services:
  instacar-api:
    build:
      context: ./instacar-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./instacar-api:/app
    depends_on:
      - db

  instacar:
    build:
      context: ./instacar
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./instacar:/app
    depends_on:
      - instacar-api

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: instacar
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: