name: instacar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  pinput: ^3.0.0
  lottie: ^3.3.1
  awesome_bottom_bar: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/instacar.png
    - assets/instacar_escrito.png
    - assets/kookies.png
    - assets/lottie/success.json
